version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
platform: x64
skip_branch_with_pr: true
install:
- cmd: set PATH="C:\Program Files (x86)\Inno Setup 6";%PATH%
build:
  parallel: true
  verbosity: minimal
after_build:
- cmd: iscc "C:\projects\zfsin\zfsinstaller\ZFSInstall-release.iss" "/Ssigntoola=C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64\signtool.exe sign /a /t http://timestamp.digicert.com /fd sha1 /d $qOpenZFS on Windows$q $f" "/Ssigntoolb=C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64\signtool.exe sign /a /as /tr http://timestamp.digicert.com /td sha256 /fd sha256 /d $qOpenZFS on Windows$q $f"
artifacts:
- path: OpenZFSOnWindows-release.exe
